query allPosts ($page: Int, $perPage: Int, $sortField: String, $sortOrder: String) {
  allPosts(page: $page, perPage: $perPage, sortField: $sortField, sortOrder: $sortOrder) {
    id
    title
    views
    User {
      name
    }
  }
}