query allPosts ($page: Int, $perPage: Int, $sortField: String, $sortOrder: String, $tag_id: ID) {
  allPosts(page: $page, perPage: $perPage, sortField: $sortField, sortOrder: $sortOrder, filter: { tag_id: $tag_id }) {
    id
    title
    views
    User {
      id
      name
    }
    Tag {
      id
      name
    }
  }
}